### ISSUE TITLE
availability time showing wrong timing

### ISSUE THREAD

**Issue by sanjaykarthic** [LibreHealthIO/LibreEHR#898] opened 2017-12-27 08:21 UTC
In calendar, make a new entry, check for available time for 'providers', it shows multiple 12;00 time slots. Pls refer below screen. is this expected.

![libre-provider-availability](https://user-images.githubusercontent.com/34680990/34375457-9fc84d46-eb0c-11e7-8459-d2baf8a515c3.png)

**Comment by teryhill** [comment] 2017-12-27 14:19
Not seeing this on the demo system or my local system.

**Comment by aethelwulffe** [comment] 2017-12-27 15:17
Check your calendar configurations. Ensure that you have the default appointment times/slots available.  Also ensure you have a provider...and patients, a facility etc...

Terry, the above was with 7 days showing in the options.  I assume you check with the same above, right?
@sanjaykarthic  What browser?  Also, are you looking at the default database?  If you scroll down in the window, what else do you see?

**Comment by teryhill** [comment] 2018-03-02 17:51
Cannot reproduce closing issue.

**Closed by teryhill** 2018-03-02 17:51 UTC
