### ISSUE TITLE
Calendar UI and Admin - Display and Config

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#727] opened 2017-10-17 17:21 UTC
As shown here the Agenda view is bad when there are a lot of doctors.   I assumed I could change the default to DAY view, but the Admin for the calendar is missing entirely 

Admin->other->calendar
The requested URL /interface/main/calendar/index.php was not found on this server.

![toomanydoctors](https://user-images.githubusercontent.com/285835/31679064-dd91ee22-b324-11e7-89df-cf9bd827e4fd.png)

**Comment by teryhill** [comment] 2017-10-17 17:49
Which system?
    On Tuesday, October 17, 2017, 1:46:39 PM EDT, Tony McCormick <notifications@github.com> wrote:  
 
 
As shown here the Agenda view is bad when there are a lot of doctors. I assumed I could change the default to DAY view, but the Admin for the calendar is missing entirely

Admin->other->calendar
The requested URL /interface/main/calendar/index.php was not found on this server.

**Comment by teryhill** [comment] 2017-10-17 17:56
You must have an outdated JSON file. It looks good in the codebase and on the demos

**Comment by teryhill** [comment] 2017-10-17 18:04
![image](https://user-images.githubusercontent.com/4655366/31680780-55d76d76-b343-11e7-8165-840273ffe5ff.png)

**Comment by teryhill** [comment] 2017-10-17 18:05
I fixed the nhanes demo site. Not sure if anyone is using it. Tony you can close this now

**Comment by tmccormi** [comment] 2017-10-17 19:20
It is being used, a lot.

But the menu is only one of the issues, the other is the UI not being able to gracefully handle a lot of doctors in agenda view.

**Comment by teryhill** [comment] 2017-10-17 19:25
Switch to day view. Most clinics will do just that.

**Comment by aethelwulffe** [comment] 2017-10-17 20:12
Paging must be possible in some manner.
We have 45 providers (or 50 maybe, don't remember) at ARSP.  Switching is fine, but an interim solution might be a warning, then a redirect to day view if the provider list is above a certain number.

**Comment by teryhill** [comment] 2017-11-17 00:23
@tmccormi @aethelwulffe @azwreith  and any one else.

I am looking at making a change to the calendar to add a "Short Name or Alternate Name" to the users file. This would be used to allow the user to specify the resources in the calendar by an alternative name. I was planning to use a global to enable the use of alternate resource name. So instead of the resource showing up as Administrator, Administrator it could be called Dr Admin.

Thoughts?

**Comment by aethelwulffe** [comment] 2017-11-17 01:09
Dude, I like that name a lot.
ATM, I am at the tail end of an 11 hour meeting....but I keep trying to review this code!

**Comment by teryhill** [comment] 2017-11-17 01:41
Have been looking at the User table. there is a field called billname but it does not appear to be used. it is referenced in addrbook_edit and lab_exchange_tools as well as some of the patient portal files. It is not , as I can see, edited by the user in any way. Could this field be re-purposed?

**Comment by teryhill** [comment] 2017-11-17 01:57
Thought's

![calendar1](https://user-images.githubusercontent.com/4655366/32925586-9d8b977a-cb10-11e7-8c66-e0c4378e9df5.PNG)

![calendar2](https://user-images.githubusercontent.com/4655366/32925602-b2c85470-cb10-11e7-9e1c-15510ff12540.PNG)

**Comment by teryhill** [comment] 2017-11-17 02:09
What about this one?

![image](https://user-images.githubusercontent.com/4655366/32925879-4de09782-cb12-11e7-8d92-169c26b7e058.png)

**Comment by aethelwulffe** [comment] 2017-11-17 12:03
Short names are great, but billname was intended for when claims were 
denied because the provider's name didn't match what was on record for 
either an NPI or other ID's from the past.  This was an issue on paper 
forms too.

Have not checked blame, but I would bet Rod or Shameem.

**Comment by yehster** [comment] 2017-11-17 12:19
Could also make it an option to display username or just lastname.

**Comment by teryhill** [comment] 2017-11-17 12:57
@yehster I will add the option to use title and lastname. @aethelwulffe I will create a field for the resource name and ditch the using of billname.

@yehster did the week layout above look better to you?

**Comment by aethelwulffe** [comment] 2017-11-17 14:00
`billname` is not being used for anything at all.  It was likely added 
for lab_exchange_tools.php

I say go ahead and use it for something...or do a find and replace on 
it.  Could have been a sql ledger thing.

**Comment by teryhill** [comment] 2017-12-05 18:51
@tmccormi if this is not complete please close it and open another issue with the remaining problem.

**Comment by teryhill** [comment] 2018-03-02 20:21
@tmccormi  if this is not complete please close it and open another issue with the remaining issue.

**Comment by aethelwulffe** [comment] 2018-03-05 19:24
This is not complete.  Put 50 providers on the calendar, and you see the same thing.  Also, put more than a handful of facilities and the same results.  We also have similar issues going unseen when tests are not done with great numbers of records in the database.  For instance, if you have 100 users, you will not be able to edit any of them due to the modal window disappearing. 
  I have not seen that this issue is yet addressed.  Agenda view need not be on for the problem to result.

**Comment by tmccormi** [comment] 2018-03-05 19:48
Agreed, we need to have a test emr setup that has preloaded a excessive number records in the "admin" areas as well as patient records.  Load testing...

**Closed** 2018-03-05 19:49 UTC
Labels: UI: Style/Menu/Label, Usability, bug
