### ISSUE TITLE
Patient Finder input error

### ISSUE THREAD

**Issue by MigDinny** [LibreHealthIO/LibreEHR#873] opened 2017-12-20 01:45 UTC
Go to Patient Finder >> look at the search inputs above each column.

The search input above "Date of Birth" should be of type="date". Currently, we are allowed to write there anything.

![image](https://user-images.githubusercontent.com/6632800/34187064-6a29fc10-e527-11e7-9466-24686ab7357f.png)

**Comment by robbyoconnor** [comment] 2017-12-20 01:51
I've verified this. Not sure if it's a bug per se..

**Comment by MigDinny** [comment] 2017-12-20 01:54
**From the task description:**
> There are going to be bugs pop up which even take an invalid data and still run successfully.

This is invalid data and the form runs successfully even though the date is invalid. I see it as a bug IMO.

**Comment by aethelwulffe** [comment] 2017-12-28 17:22
Yeah, I see this as a bug...or a feature.  The issue is that the search can be configured to have any demographics element in it, so it would need to recognize the data type.  Also, you might want to only select a year or a month or anything like that to find anyone turning 40 this month or something like that.  It would need to be either free-form, or very loosely typed.
  If it can be "fixed" without it becoming less useful, then it is a bug.
...something of a hard case to judge.

**Comment by MigDinny** [comment] 2017-12-28 17:27
@aethelwulffe we can let it be this way or change its type to "date". I can do it if needed

**Comment by teryhill** [comment] 2018-03-02 18:26
Closing this issue. This is the current nature of the finder.

**Closed by teryhill** 2018-03-02 18:26 UTC
Labels: Consistency/Code Formatting
