### ISSUE TITLE
Missing Titles

### ISSUE THREAD

**Issue by Jdew192837** [LibreHealthIO/LibreEHR#888] opened 2017-12-25 14:35 UTC
Merry Christmas!
====

There are missing titles in some files of "Patient/Client" "Visit Forums" under the subsections:

 'Misc Billing Options for HCFA-1500'

'Review of Systems'

Screenshots:
====
![screenshot 90](https://user-images.githubusercontent.com/24306897/34340684-4b002b0e-e94e-11e7-8f73-bc7bae42a3f3.png)
====
![screenshot 89](https://user-images.githubusercontent.com/24306897/34370786-aae2c13c-ea8c-11e7-851e-c671ea0d37dc.png)

Thanks,
jdew192837

**Comment by Jdew192837** [comment] 2017-12-26 17:12
@Trodrige @teryhill Mind taking a look at these fixes I made for this issue?
Thanks,
jdew192837

**Comment by aethelwulffe** [comment] 2017-12-27 23:58
No PR linked.

Typically, along with the fix, you want to hide the actual form title so i just shows in the tab...at least in the normal view.  A report view can include it.

**Comment by Jdew192837** [comment] 2017-12-28 00:46
@aethelwulffe Commented on the wrong issue, but can this issue be verifed by you?

**Comment by aethelwulffe** [comment] 2017-12-28 15:42
I don't think the comment was wrong, but I see what you are saying.
  The issue is verified.  The title in the form is not being picked up by the tab.

Visit forms, meaning clinical or encounter forms, are located under interface/forms/form_name.  Some are very very old, and none of them are really any good or are useful.  The Review of Systems form is one of those.  The HCFA form did (I believe, could be wrong) have a title that reflected in the tab at one point.  That form is associated with billing, and therefore gets updated fairly often, which is what could have happened with this.

By all means claim this as a bug find.  This exists in at least two forms, so this issue is a two-for-one.  You could (should) separate them into two issues as they involve two forms, and should probably have two PR's to fix them.

**Comment by Jdew192837** [comment] 2017-12-28 16:18
Okay, @aethelwulffe So this issue I filed upon resolution will count as two bug fixes?

**Comment by aethelwulffe** [comment] 2017-12-28 16:22
If you are fixing what looks like the same bug in more than one place by altering the code in each instance, that is more than one bug.
-Yes...this is two bugs.
🐛 🐞

**Comment by Jdew192837** [comment] 2017-12-28 16:24
Okay, thanks @aethelwulffe could you check this issue, I filed does it qualify as Function Conjuction 1 #884

**Comment by aethelwulffe** [comment] 2017-12-28 16:30
No.  These qualify as bug fixes.  No worry, you might be able to find more of these in other forms, especially if the enble form forms in the administration/forms.  Heck you might find different bugs there!

**Comment by aethelwulffe** [comment] 2017-12-28 16:35
Oh, wait, you mean some other issue.  Yes, #884 does not exactly match the conditions there, but yes, the idea is right.  In this case you are still taking corrective action on a replicated function...just by deleting it.  That has nothing to do with this issue though....keep your context concise to the thread. 😸

**Comment by Jdew192837** [comment] 2017-12-28 16:37
@aethelwulffe There is someone on chat that has been waiting a while for task to be reviewed username is @Vishwas-Adiga

**Comment by aethelwulffe** [comment] 2017-12-28 16:38
Thank you.
I am barely able to keep up with the PR's here (and some of the issues) much less attend to the chat.  I will check, then I have to get some work done.

**Comment by aethelwulffe** [comment] 2017-12-28 17:07
@Jdew192837 thanks for that heads up.  It was a really good submission too!

**Comment by Jdew192837** [comment] 2018-01-07 19:17
Ping @teryhill, @aethelwulffe  :)

**Comment by teryhill** [comment] 2018-03-02 18:02
PR's Merged Closing Issue

**Closed by teryhill** 2018-03-02 18:02 UTC
Labels: GCI Task, Multiple Issues, UI: Style/Menu/Label, bug
