### ISSUE TITLE
need to make a directory to house the tools used in system development

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#372] opened 2017-01-31 22:17 UTC
currently there are jquery files and tools stored in the /library/js directory. These are what is stored there:

ajax_functions_writer.js
ajtooltip.js
blink
calendarDirectSelect.js
clickmap.js
common.js
datatables
DocumentTreeMenu.js
fancybox
fancybox-1.3.4
jquery-1.2.2.min.js
jquery-1.4.2.min.js
jquery-1.4.3.min.js
jquery-1.5.js
jquery-1.6.4.min.js
jquery-1.7.2.min.js
jquery-1.9.1.min.js
jquery-2.2.0.min.js
jquery-calendar.css
jquery-calendar.js
jquery-ui-1.7.1.custom.min.js
jquery-ui-1.8.21.custom.min.js
jquery-ui-1.8.6.custom.min.js
jquery-ui.js
jquery.1.3.2.js
jquery.autocomplete.pack.js
jquery.bgiframe.min.js
jquery.cookie.js
jquery.dimensions.pack.js
jquery.easydrag.handler.beta2.js
jquery.gritter.min.js
jquery.js
jquery.livequery101.js
jquery.treeview-1.3
jquery.treeview-1.4.1
jquery121.js
jscolor
jscolor-1-4-5
knockout
qtip
SearchHighlight.js

in this directory (interface\tags_filters\assets)  the following assets are listed

jQuery JavaScript Library v1.9.1 (multiple copies)
Bootstrap v3.3.6
Bootstrak editable - v1.5.1
data_table
jquery.datetimepicker
jquery.validate
moment.min.js
bootstrap3-typeahead.js
Select2 4.0.2
jQuery Migrate - v1.1.0
RequireJS 2.1.5
composer (also in /library/vendor)

I think we should decide on a directory and move all the stuff there to cut out the replication

**Comment by aethelwulffe** [comment] 2017-01-31 22:23
How does this sound?:

Make a location.

Start moving them one-by-one (or more) with a commit, tests, and search 
results posted for each commit.

Immediately, you could create that location (or re-use library/js) for 
the portal.

I tend to prefer migrating to a new directory name because when you move 
it /and/or upgrade the version/ and you have not checked everything out, 
something doesn't work...and we find out about it

**Comment by teryhill** [comment] 2017-01-31 22:32
I like the slow and steady approach and migrating to a different directory. I think we should try to get everything to the latest version and if it will not work on that version figure out why and fix it. @tmccormi has a csv file with the jquery's and that would be a start. Load a directory with the latest jquery and then start migrating the code.

**Comment by tmccormi** [comment] 2017-01-31 22:45
it's attached to #323

**Comment by teryhill** [comment] 2017-01-31 22:51
@tmccormi  's statement "Industry standard is to put 'shared' assets in the vendor/ directory structure." would lead to using /libreehr/vendor/tools  or assets

**Comment by teryhill** [comment] 2017-01-31 23:40
after web searches it appears that the structure should be /public/assets then there is a choice, we can pile them all in the directory or make sub directories for JS, CSS, IMAGES ... You guys make the call. @tmccormi  @aethelwulffe  @kchapple

**Comment by tmccormi** [comment] 2017-01-31 23:42
I prefer the subdirs organized

**Comment by aethelwulffe** [comment] 2017-01-31 23:46
Honestly, these qualify as /lib and not /vendor assets as-per industry 
norm.  These are core, as they are part of our "framework".

...buuuut, anything at all is fine.  The commoners will never recognize 
the distinction!

**Comment by teryhill** [comment] 2017-01-31 23:55
so is it libreehr/public/assets or libreehr/assets  with JS,CSS and IMAGES for a start

**Comment by aethelwulffe** [comment] 2017-01-31 23:57
Tony is right about Ruby and some other frameworks, I am right where 
real progra...uh other languages are concerned, and you are right 
concerning a significant fraction of everything else.

Libraries/public/assets or just /public/assets is fine.  I don't care, 
because there isn't anything close to a standard, and everyone pretty 
much recognizes what they are looking at there...if we only have one and 
not all of them!.  What else would go under /public?

**Comment by aethelwulffe** [comment] 2017-02-01 00:01
libreehr/vendor_assets ?:-P

**Comment by tmccormi** [comment] 2017-02-01 00:01
Look at the FHIR and Core Repos and see what @kchapple did ...

**Comment by tmccormi** [comment] 2017-02-01 00:04
never mind both of those repos are so clean they don't any added vendor assets :-)

**Comment by aethelwulffe** [comment] 2017-02-01 01:46
JS chunks from third parties and the like are LIBRARIES.

Fonts, images and junk like that are ASSETS.

VENDOR would only be used for LIBRARIES if they came from a FRAMEWORK 
that the application was built on top of, otherwise VENDOR goes under 
ASSETS for those pieces that came from elsewhere.

Unfortunately, we already have libraries/js, and we want to move off of 
that...and some of the nerds here like the name VENDOR...

so, I am going to push a commit that creates libreehr/vendor/js and /css 
and all that shit, and you can merge it and use it or no. ;-)

**Comment by kchapple** [comment] 2017-02-01 15:07
The "vendor" is a composer convention. Dependencies are specified in composer.json, like Doctrine 2.*, or PHPMail 1.0, or jQuery 1.9.* or whatever. The thing is that in most systems, we don't want our javascripts in a vendor directory because that's a server-side directory that supports auto-loading of PHP via composer's autoloaders (completely useless for JS.) So you can use a client-side package manager (like OpenEMR adopted bower I believe) or use a post-install command to move JS scripts from vendor to their proper home. Now, what is the proper home?  In most systems these days, there is a "public" directory like you guys are discussing. In this system, however, every directory is public. In our case I think an "includes/js/name_of_library/some_code.js" or "interface/includes/js..." is appropriate. I don't really see anything wrong with library/js until we put some kind of dependency-management system and script queuing system in place.

**Comment by kchapple** [comment] 2017-02-01 15:12
I agree with Terry, though, that duplicate stuff should be normalized. The Tags/Filter codes was meant to be an isolated plugin, not part of the main code base, though.

**Comment by aethelwulffe** [comment] 2017-02-01 19:24
Yeah, I already dumped the idea of using vendor for third party stuff due to composer issues...until composer is handling those!  The Enterprise-centric minds think that is the was to do stuff, but I don't think the average windows OS-swinging doctor is going to install a web server, download composer and get cracking on the command line to do anything.

  I personally think that /vendor is one of the worst of the liberal-arts-challenged term choices a code monkey has ever come up with, but I thought it would please and sparkle.  The js libraries should indeed go in lib/js.  I agree.  The issue is that there is the organization project, so we are trying to come up with migration/strangle-vine schemes that let us do that easily, and moving the libraries to a new directory as they are "checked in" is one of those.

So, if we decide that /libraries could contain non-native 3rd party js files due to the fact that they are used by the Core of the application, that is fine, but then the issue of packing special libraries for optional components in a location where we are maintaining the code becomes problematic.

###   I would suggest the following:
Reserve /libraries for includes and dependencies that are the core and are maintained locally.  Things in there should mostly be named .inc or php.inc.  We should start moving files directly under libraries into meaningfully named subdirectories.  If we want to include 3rd party bits in there, like the usual .js stuff, then we might consider migrating to /jslib so we can keep a cleanup program going easily.

###   Next, move image assets to a couple of different places:
For thematic/css elements that are not related to branding (sites), I think we should move them to interface/themes/theme_assets.  That includes files like aquabg.gif, the css buttons and the like as in #378.  Everything else not a code library in /library should go to /assets.  This includes fonts, especially those damn minimized fonts named .php that are always messing with grep results.

### Decide what the heck a module is.
1.  A plug-in is exactly that.  You drop in the code, register the plugin, and it just works.  Typically there are core components (a core "module") that handles this stuff, and uses the same process for all of them.  The forms system is a plug-in system, so we have those.  They are only affected with the core plugin module changes.  

2.  A Mod (modification) has two components:

- Modifications to the core files.
- Other files it adds.

Ideally, Mods get treated in the following way:

- They are registered in some way.
- The changes to the core code are documented, preferably with a change document included in the modification, or a fancy-schmancy automated mod tool.

Files added by a Mod are treated in one of two ways:

- Contained in a MODULES directory that houses 3rd party directories.  Each Module has it's own dependencies, resources etc... and we never ever need worry if the author is using core libraries or their own versions.
- Spread out into a directory structure that organizes their code like the "assets" idea above.  I actually hate that idea.

**Comment by aethelwulffe** [comment] 2017-02-11 18:41
Starting an issue for the jquery upgrade itself.

**Comment by aethelwulffe** [comment] 2017-03-02 22:55
Issue finished.

**Closed by aethelwulffe** 2017-03-02 22:55 UTC
