### ISSUE TITLE
Patient ledger report needs to say no data to display , Currently it just disappears. 

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#1057] opened 2018-03-11 16:57 UTC
The patient ledger report results aren't displayed long enough.
- Fill the form and submit.
Observe the results show up, and disappear almost immediately.

**Comment by teryhill** [comment] 2018-03-14 02:15
@Trodrige  it will do that if there is nothing to display.

**Comment by amughalbscs16** [comment] 2018-03-18 17:56
@teryhill please share an image so, I can work on resolving the matter. Please specifically address where is the problem coming.

**Comment by aethelwulffe** [comment] 2018-03-19 01:17
Yeah, posting menu breadcrumbs or full "reproduce this" instructions might be a good standard while GSOC is going on.

**Comment by amughalbscs16** [comment] 2018-03-19 04:46
@aethelwulffe where on which page is this error coming, I am searching for it. guide me where is the error coming so I can solve it.

**Comment by teryhill** [comment] 2018-03-19 19:05
Select a patient and then select ledger from the demographics screen.

![image](https://user-images.githubusercontent.com/4655366/37616624-ebb26484-2b86-11e8-82e6-d0be646d27de.png)

**Comment by amughalbscs16** [comment] 2018-03-20 13:38
what should be displayed do you want a modal to open or an alert which tells the patient that no records were found?

**Comment by amughalbscs16** [comment] 2018-03-20 13:42
I think there should be an alert or a modal opening which tells the user that 0 records were found.

**Comment by teryhill** [comment] 2018-03-20 13:48
Sounds good to me. An alert would be best I think since this can also be ran from the report menu.

**Comment by amughalbscs16** [comment] 2018-03-20 13:49
Plus a sleep for 5 seconds which will help user see the empty table as well
with the alert?

**Comment by teryhill** [comment] 2018-03-20 14:04
Okay

**Comment by amughalbscs16** [comment] 2018-03-20 14:31
I thought putting a sleep wouldn't be the best option, so I added an alert when there are no records to show. Here is the link to the pull request. https://github.com/LibreHealthIO/LibreEHR/pull/1067.
Solved.

**Comment by Trodrige** [comment] 2018-03-21 07:40
@amughalbscs16 I noticed you solved this after doing a PR. I used another approach. 
1. The table doesn't appear if there's no result and
2. The message is in red.

I'm not going to steal this from you! This is how my change looks like.

![patient-ledger](https://user-images.githubusercontent.com/16147419/37698494-7f3c1dfa-2ce3-11e8-815f-50436ce04068.png)

**Comment by amughalbscs16** [comment] 2018-03-21 07:59
I have given a screenshot of the solution in the PR it shows an alert only.
when there are no records.

**Comment by aethelwulffe** [comment] 2018-03-21 13:35
We have GOT to get assignments worked out here.  Too many cool people are working on great solutions...for the same things.
-Good work all by the way.  @amughalbscs16  Ali, I need to send you an invitation to the repo.  Remind me if I don't get it done within the next 12 hours or so.

**Comment by amughalbscs16** [comment] 2018-03-22 03:08
@aethelwulffe Just a reminder, please send me an invitation to the repository. Thank you very much.

**Closed** 2018-03-22 23:01 UTC
Labels: Feature: Reports, GSoC2018, bug
