### ISSUE TITLE
Michael Downey profile on the website landing page

### ISSUE THREAD

**Issue by techfreakSahil** [LibreHealthIO/LibreEHR#1681] opened 2022-11-28 13:36 UTC
Others profile when hovered over is lightened except Mr. Michael Downey's profile.
![Screenshot (42)](https://user-images.githubusercontent.com/116283802/204291098-a993e7db-36c1-4fe4-9179-9c21718d18b1.png)

**Comment by sunbiz** [comment] 2022-12-01 07:24
Closing since the issue is at the incorrect repo. Correct repo should be -  https://gitlab.com/librehealth/lsc/librehealth.io
@techfreakSahil, please feel free to create the issue and send a merge request.

**Closed as completed by sunbiz** 2022-12-01 07:24 UTC

**Comment by techfreakSahil** [comment] 2022-12-01 12:44
Thanks for the response Sir.
I would like to explore this project and contribute meaningfully to it.
